#ifndef _QUCC_H
#define _QUCC_H

#define QUCC_RX_SUCCESS 1
#define QUCC_RX_FAIL 0

#define QUCC_RX_VALID 1
#define QUCC_RX_INVALID 0

#define QUCC_RX_START_IDX 0
#define QUCC_RX_START_LEN 1
#define QUCC_RX_START_VAL 0xDD

#define QUCC_RX_COMMAND_IDX 1
#define QUCC_RX_COMMAND_LEN 1

#define QUCC_RX_STATUS_IDX 2
#define QUCC_RX_STATUS_LEN 1

#define QUCC_RX_LENGTH_IDX 3
#define QUCC_RX_LENGTH_LEN 1

#define QUCC_RX_DATA_IDX 4
#define QUCC_RX_DATA_LEN 0

#define QUCC_RX_CHECKSUM_IDX
#define QUCC_RX_CHECKSUM_LEN 2
#define QUCC_RX_CHECKSUM_VAL

#define QUCC_RX_END_IDX
#define QUCC_RX_END_LEN 1
#define QUCC_RX_END_VAL 0x77

#define QUCC_RX_CHECKSUM_START_IDX (QUCC_RX_STATUS_IDX)
#define QUCC_RX_CHECKSUM_BYTE_LEN (QUCC_RX_STATUS_LEN+QUCC_RX_LENGTH_LEN+QUCC_RX_DATA_LEN)

#endif